### ISSUE TITLE
How to get dictionary?

### ISSUE THREAD

**Issue by luckytoilet** [jonathandunn/c2xg#1]
Hi, I'm trying to play around with this project, but I'm having trouble getting it set up. I am unable to create the C2xG class because the dictionary is missing:

`FileNotFoundError: [Errno 2] No such file or directory: 'c2xg/c2xg/modules/../data/dictionaries/eng.POS.2000dim.2000min.20iter.POS_Clusters.p'`

Is this supposed to be downloaded or generated somewhere?

**Comment by jonathandunn** [comment]
The dictionaries are in the process of being updated. For now the easiest approach is to checkout the last tagged release: 0.02
